### ISSUE TITLE
Build flow isn't working

### ISSUE THREAD

**Issue by quii** [mergermarket/goMakeIt#6]
It seems that the volume mapping is wrong or something? 

If you make a code change and then do `run-locally.sh` your changes aren't reflected. You can fix this with `docker-compose build` but it shouldn't be necessary to rebuild the image just for code changes.

**Comment by gypsydave5** [comment]
Should be fixed by [8bb8ef4 ](https://github.com/mergermarket/goMakeIt/commit/8bb8ef4cecc6a3346832802959d52541b7ba4663)

**Comment by quii** [comment]
Works for sures
